### ISSUE TITLE
"Send all [asset]" wants to send unrelated assets too 

### ISSUE THREAD

**Issue by AliHoussein** [Emurgo/yoroi-mobile#1838] opened 2021-12-16 05:30 UTC
Hi everyone,

Trying to send some assets between wallets, there might be a bug when using the the 'Send all" checkbox.

When checking the "Send all [asset]" for a given transaction 
![IMG_DDF1AAF20D09-1](https://user-images.githubusercontent.com/294671/146313285-0997ad5d-651d-42d7-863c-22c05f569e1e.png)
 
The wallet shows a warning, however displays that it wants to send all the assets in the wallet
![sending all hosk](https://user-images.githubusercontent.com/294671/146313786-2a2164ad-b82a-4a4f-a3ad-91966865012f.PNG)

The feature works properly with the browser extension.

**Comment by zuzunker** [comment] 2021-12-16 07:49
Hi, @AliHoussein ! Thank you for the report, we are investigating this top priority at the moment.

Can you please clarify and that would help a lot with resolving the problem, in this case - are these ALL the tokens you have at all in that wallet, or only some of them? It would be really really helpful to us to clarify if it tries to send ALL tokens you have or only selects SOME of them.

![image](https://user-images.githubusercontent.com/5585355/146329684-12664474-0a43-4d89-919c-54a31cc1ecac.png)

**Comment by zuzunker** [comment] 2021-12-16 08:35
@AliHoussein , which version of the app do you have, btw, and which operating system?

**Comment by zuzunker** [comment] 2021-12-16 11:17
The issue is investigated. This is a displaying problem. The actual constructed transaction is correct and will only send the selected asset, but it incorrectly displays some accidental assets just because they are getting mixed in with the inputs. But they are not leaving the wallet in reality. This displaying is being fixed atm and the new version 4.5.2 will be pushed right after

**Comment by AliHoussein** [comment] 2021-12-17 02:08
Hi @vsubhuman thanks for the swift review! 

To answer your questions : 
- it was showing indeed all the other assets I have in the wallet
- I am running iOS 15.0, yoroi version 4.4.2 

Glad to see you identified the bug, and looking forward to downloading the update

Cheers,
Ali

**Comment by zuzunker** [comment] 2021-12-19 17:19
Fixed in version 4.5.2 which is bein deployed at the moment

**Closed as completed by zuzunker** 2021-12-19 17:19 UTC
Labels: bug (confirmed)
