### ISSUE TITLE
API Error when sending from Yoroi + Ledger

### ISSUE THREAD

**Issue by dirtymike0330** [Emurgo/yoroi-mobile#856] opened 2020-07-24 02:22 UTC
Getting the API Error: Error received from api method call while sending transaction when trying to send from Yoroi Mobile + Ledger. I pulled the 2.2.3 apk, but the problem remains.

**Comment by v-almonacid** [comment] 2020-07-24 06:35
This is very unfortunate. However, we cannot fix this because we are busy working on Shelley integration. Even if we fixed it, the fix might never see the light of day because the Byron network will be shutdown in a few days (which can happen before the issue is identified and the fix merged and released by the Apple/Google stores).

**Closed as completed by v-almonacid** 2020-07-24 06:35 UTC

**Comment by dirtymike0330** [comment] 2020-07-24 07:11
So your solution is "sorry we're too busy, your funds are trapped"? Gee, thanks.

**Comment by SebastienGllmt** [comment] 2020-07-24 07:23
Your funds aren't trapped. You can still access them from the Yoroi Extension or AdaLite
However, with the upcoming Shelley hardfork next week on the 29th, your Ledger device itself will need to be updated and Ledger hasn't given a date for when the update will happen so you should expect some time where you won't be able to access your funds.

**Comment by dirtymike0330** [comment] 2020-07-24 07:25
> Your funds aren't trapped. You can still access them from the Yoroi Extension or AdaLite
> However, with the upcoming Shelley hardfork next week on the 29th, your Ledger device itself will need to be updated and Ledger hasn't given a date for when the update will happen so you should expect some time where you won't be able to access your funds.

I tried to recover using my 15 words through the chrome extension but it shows no balance. My ledger is setup through the mobile app.

**Comment by v-almonacid** [comment] 2020-07-24 07:31
You don't need to use your recovery phrase. Rather, you need to go through the "Connect to hardware wallet" option.

**Comment by dirtymike0330** [comment] 2020-07-24 07:37
Ok, that worked. Thanks. Sorry for the frustration.

**Comment by v-almonacid** [comment] 2020-07-24 07:41
Glad to know that. We are sorry too about these issues. This is a period of fast development which involves many breaking changes. We would love to have the time to address every single issue but unfortunately it's not always possible.
